{% set version = "12.4.1" %}

package:
  name: nvidia-gds
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 1
  skip: true  # [not (linux64 or aarch64)]

requirements:
  run:
    - libcufile 1.9.1.3
    - libcufile-dev 1.9.1.3
    - libcufile-static 1.9.1.3
    - gds-tools 1.9.1.3

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: GPU Direct Storage meta-package
  description: |
    Meta-package containing all the available packages required for libcufile.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
